config/routes.rb
Pearl::Application.routes.draw do
  devise_for :users

  resources :users, :only => [:index, :show, :destroy] do
    post :select_group, :on => :collection
    get :edit_profile, :on => :collection
    post :update_profile, :on => :collection
    get :cancel_user, :on => :collection
  end

  resources :projects do
    get :finish, :on => :collection
    resources :documents
  end

  resources :papers do
    resources :documents
  end

  resources :patents do
    resources :documents
  end

  match '/theses/my' => 'theses#my'
  resources :theses do
    resources :documents
  end

  resources :reviews, :only => [:create, :destroy]

  match '/dailies/my(/:date)' => 'dailies#my'
  match '/dailies/group(/:date)' => 'dailies#group'
  match '/dailies/subgroup(/:date)' => 'dailies#subgroup'
  resources :dailies, :only => [:index, :show, :edit, :create, :update]

  resources :comments, :only => [:create, :destroy]

  match '/plans/user(/:id)' => 'plans#user'
  resources :plans do
    get :update_status, :on => :collection
  end

  resources :groups

  match '/home/index/(/:all)' => 'home#index'

  root :to => 'home#index'

end

app/models/document.rb
# == Schema Information
#
# Table name: documents
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  content    :text
#  user_id    :integer
#  project_id :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  category   :integer
#  paper_id   :integer
#  patent_id  :integer
#  thesis_id  :integer
#

class Document < ActiveRecord::Base
  has_many :reviews
  belongs_to :user
  belongs_to :project
  belongs_to :paper
  belongs_to :patent
  belongs_to :thesis

  attr_accessible :title, :content, :category

  validates :title,       :presence => true

  validates :user_id,     :presence => true

  validates :category,    :presence => true,
                          :numericality => {:only_integer => true}
end

app/controllers/documents_controller.rb
# coding: utf-8

class DocumentsController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource

  def index
    common_vars
    if @documents.size > 0
      @document = @documents[0]
    else
      @document = Document.new
    end
    @reviews = @document.reviews
    @review = Review.new
    @floor = 0
  end

  def show
    common_vars
    @document = Document.find(params[:id])
    @reviews = @document.reviews
    @review = Review.new
    @floor = 0
  end

  def new
    common_vars
    @document = Document.new
  end

  def edit
    common_vars
    @document = Document.find(params[:id])
  end

  def create
    @document = Document.new(params[:document])
    @object = nil
    @category = nil
    if params[:project_id]
      @category = Setting.documents.category_project
      @object = Project.find(params[:project_id])
      @document.project = @object
    elsif params[:paper_id]
      @category = Setting.documents.category_paper
      @object = Paper.find(params[:paper_id])
      @document.paper = @object
    elsif params[:patent_id]
      @category = Setting.documents.category_patent
      @object = Patent.find(params[:patent_id])
      @document.patent = @object
    elsif params[:thesis_id]
      @category = Setting.documents.category_thesis
      @object = Thesis.find(params[:thesis_id])
      @document.thesis = @object
    end
    @document.category = @category
    @document.user = current_user

    if @document.save
      if @category == Setting.documents.category_project
        redirect_to project_document_url(@object, @document)
      elsif @category == Setting.documents.category_paper
        redirect_to paper_document_url(@object, @document)
      elsif @category == Setting.documents.category_patent
        redirect_to patent_document_url(@object, @document)
      elsif @category == Setting.documents.category_thesis
        redirect_to thesis_document_url(@object, @document)
      else
        redirect_to root_url
      end
    else
      flash[:error] = "输入内容缺失或存在错误，新建文档失败！"
      if @category == Setting.documents.category_project
        redirect_to new_project_document_url(@object)
      elsif @category == Setting.documents.category_paper
        redirect_to new_paper_document_url(@object)
      elsif @category == Setting.documents.category_patent
        redirect_to new_patent_document_url(@object)
      elsif @category == Setting.documents.category_thesis
        redirect_to new_thesis_document_url(@object)
      else
        redirect_to root_url
      end
    end
  end

  def update
    @document = Document.find(params[:id])
    @object = nil
    @category = nil
    if params[:project_id]
      @category = Setting.documents.category_project
      @object = Project.find(params[:project_id])
    elsif params[:paper_id]
      @category = Setting.documents.category_paper
      @object = Paper.find(params[:paper_id])
    elsif params[:patent_id]
      @category = Setting.documents.category_patent
      @object = Patent.find(params[:patent_id])
    elsif params[:thesis_id]
      @category = Setting.documents.category_thesis
      @object = Thesis.find(params[:thesis_id])
    end

    if @document.update_attributes(params[:document])
      if @category == Setting.documents.category_project
        redirect_to project_document_url(@object, @document)
      elsif @category == Setting.documents.category_paper
        redirect_to paper_document_url(@object, @document)
      elsif @category == Setting.documents.category_patent
        redirect_to patent_document_url(@object, @document)
      elsif @category == Setting.documents.category_thesis
        redirect_to thesis_document_url(@object, @document)
      else
        redirect_to root_url
      end
    else
      flash[:error] = "输入内容缺失或存在错误，编辑文档失败！"
      if @category == Setting.documents.category_project
        redirect_to edit_project_document_url(@object, @document)
      elsif @category == Setting.documents.category_paper
        redirect_to edit_paper_document_url(@object, @document)
      elsif @category == Setting.documents.category_patent
        redirect_to edit_patent_document_url(@object, @document)
      elsif @category == Setting.documents.category_thesis
        redirect_to edit_thesis_document_url(@object, @document)
      else
        redirect_to root_url
      end
    end
  end

  def destroy
    @document = Document.find(params[:id])
    @document.destroy
    @object = nil
    if params[:project_id]
      @object = Project.find(params[:project_id])
      redirect_to project_documents_url(@object)
    elsif params[:paper_id]
      @object = Paper.find(params[:paper_id])
      redirect_to paper_documents_url(@object)
    elsif params[:patent_id]
      @object = Patent.find(params[:patent_id])
      redirect_to patent_documents_url(@object)
    elsif params[:thesis_id]
      @object = Thesis.find(params[:thesis_id])
      redirect_to thesis_documents_url(@object)
    else
      redirect_to root_url
    end
  end

  private

  def common_vars
    @object = nil
    @category = nil
    @documents = []
    if params[:project_id]
      @category = Setting.documents.category_project
      @object = Project.find(params[:project_id])
    elsif params[:paper_id]
      @category = Setting.documents.category_paper
      @object = Paper.find(params[:paper_id])
    elsif params[:patent_id]
      @category = Setting.documents.category_patent
      @object = Patent.find(params[:patent_id])
    elsif params[:thesis_id]
      @category = Setting.documents.category_thesis
      @object = Thesis.find(params[:thesis_id])
    end
    @documents = @object.documents
  end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_form.html.haml
= form_for [@object, @document], :validate => true do |f|
  - if @document.errors.any?
    #error_explanation
      %h2= "#{pluralize(@document.errors.count, "error")} prohibited this document from being saved:"
      %ul
        - @document.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.text_field :title, :placeholder=>"输入文档标题", :class=>"form-control"

  .form-group
    = f.kindeditor :content, :height=>300, :simple_mode => true, :class=>"form-control"

  .form-group
    = f.submit '保存', :class=>"btn btn-default"

app/views/documents/_index.html.haml
%h3.wall-header
  .wall-header-content
    .row
      .col-md-4
        全部文档
      .col-md-3.col-md-offset-5
        - if @category == Setting.documents.category_project
          = link_to '新建文档', new_project_document_path(@object), :class=>"btn btn-default"
        - elsif @category == Setting.documents.category_paper
          = link_to '新建文档', new_paper_document_path(@object), :class=>"btn btn-default"
        - elsif @category == Setting.documents.category_patent
          = link_to '新建文档', new_patent_document_path(@object), :class=>"btn btn-default"
        - elsif @category == Setting.documents.category_thesis
          = link_to '新建文档', new_thesis_document_path(@object), :class=>"btn btn-default"
%br

%table.table.table-hover
  - @documents.each do |document|
    %tr
      %td
        .row
          .col-md-7
            = link_to document.title, [@object, document]
          .col-md-2
            = document.user && document.user.name
          .col-md-3
            = document.created_at.strftime("%m-%d %H:%M")

app/views/documents/_show.html.haml
- if @document
  = @document.content.html_safe

%hr
.comments
  - @reviews.each do |review|
    .row
      .col-md-12
        .panel.panel-default
          .panel-heading
            .row
              .col-md-10
                - @floor += 1
                = "#{@floor} 楼"
                = link_to review.user.name, review.user
                = "#{review.created_at.strftime("%Y-%m-%d %H:%M")} 发表"
              .col-md-2
                - if can? :destroy, review
                  = link_to '删除', review, :method => :delete, :data => { :confirm => 'Are you sure?' }
          .panel-body
            = review.content

%h5 发表评论
= form_for @review, :html=>{:class=>"form-horizontal"} do |f|
  .form-group
    .col-md-10
      = f.text_area :content, :value=>@review.content, :rows=>5, :class=>"form-control"
      = f.hidden_field :document_id, :value=>@document.id
    = f.submit '提交', :class=>"btn btn-success"

app/views/documents/edit.html.haml
- if @category == Setting.documents.category_project
  = render "projects/sub_navbar"
- elsif @category == Setting.documents.category_paper
  = render "papers/sub_navbar"
- elsif @category == Setting.documents.category_patent
  = render "patents/sub_navbar"
- elsif @category == Setting.documents.category_thesis
  = render "theses/sub_navbar"

.row
  .col-md-5.wall
    = render "index"

  .col-md-7.wall
    %h3.wall-header
      .wall-header-content
        .row
          .col-md-9
            - if @document
              = "正在编辑：#{@document.title}"
          .col-md-3
    %br

    = render "form"

app/views/documents/index.html.haml
- if @category == Setting.documents.category_project
  = render "projects/sub_navbar"
- elsif @category == Setting.documents.category_paper
  = render "papers/sub_navbar"
- elsif @category == Setting.documents.category_patent
  = render "patents/sub_navbar"
- elsif @category == Setting.documents.category_thesis
  = render "theses/sub_navbar"

.row
  .col-md-5.wall
    = render "index"

  .col-md-7.wall
    - if @documents.size > 0
      %h3.wall-header
        .wall-header-content
          .row
            .col-md-9
              - if @document
                = @document.title
            .col-md-3
              - if @document
                - if @category == Setting.documents.category_project
                  - if can? :update, @document
                    = link_to '编辑', edit_project_document_path(@object, @document), :class=>"btn btn-default"
                  - if can? :destroy, @document
                    = link_to '删除', [@object, @document], :method => :delete, :data => { :confirm => 'Are you sure?' }, :class=>"btn btn-default"
                - elsif @category == Setting.documents.category_paper
                  - if can? :update, @document
                    = link_to '编辑', edit_paper_document_path(@object, @document), :class=>"btn btn-default"
                  - if can? :destroy, @document
                    = link_to '删除', [@object, @document], :method => :delete, :data => { :confirm => 'Are you sure?' }, :class=>"btn btn-default"
                - elsif @category == Setting.documents.category_patent
                  - if can? :update, @document
                    = link_to '编辑', edit_patent_document_path(@object, @document), :class=>"btn btn-default"
                  - if can? :destroy, @document
                    = link_to '删除', [@object, @document], :method => :delete, :data => { :confirm => 'Are you sure?' }, :class=>"btn btn-default"
                - elsif @category == Setting.documents.category_thesis
                  - if can? :update, @document
                    = link_to '编辑', edit_thesis_document_path(@object, @document), :class=>"btn btn-default"
                  - if can? :destroy, @document
                    = link_to '删除', [@object, @document], :method => :delete, :data => { :confirm => 'Are you sure?' }, :class=>"btn btn-default"
      %br

      = render "show"
    - else
      %h3.wall-header
        .wall-header-content
          .row
            .col-md-9
              新建文档
            .col-md-3
      %br

      = render "form"

app/views/documents/new.html.haml
- if @category == Setting.documents.category_project
  = render "projects/sub_navbar"
- elsif @category == Setting.documents.category_paper
  = render "papers/sub_navbar"
- elsif @category == Setting.documents.category_patent
  = render "patents/sub_navbar"
- elsif @category == Setting.documents.category_thesis
  = render "theses/sub_navbar"

.row
  .col-md-5.wall
    = render "index"

  .col-md-7.wall
    %h3.wall-header
      .wall-header-content
        .row
          .col-md-9
            新建文档
          .col-md-3
    %br

    = render "form"

app/views/documents/show.html.haml
- if @category == Setting.documents.category_project
  = render "projects/sub_navbar"
- elsif @category == Setting.documents.category_paper
  = render "papers/sub_navbar"
- elsif @category == Setting.documents.category_patent
  = render "patents/sub_navbar"
- elsif @category == Setting.documents.category_thesis
  = render "theses/sub_navbar"

.row
  .col-md-5.wall
    = render "index"

  .col-md-7.wall
    %h3.wall-header
      .wall-header-content
        .row
          .col-md-9
            - if @document
              = @document.title
          .col-md-3
            - if @document
              - if @category == Setting.documents.category_project
                - if can? :update, @document
                  = link_to '编辑', edit_project_document_path(@object, @document), :class=>"btn btn-default"
                - if can? :destroy, @document
                  = link_to '删除', [@object, @document], :method => :delete, :data => { :confirm => 'Are you sure?' }, :class=>"btn btn-default"
              - elsif @category == Setting.documents.category_paper
                - if can? :update, @document
                  = link_to '编辑', edit_paper_document_path(@object, @document), :class=>"btn btn-default"
                - if can? :destroy, @document
                  = link_to '删除', [@object, @document], :method => :delete, :data => { :confirm => 'Are you sure?' }, :class=>"btn btn-default"
              - elsif @category == Setting.documents.category_patent
                - if can? :update, @document
                  = link_to '编辑', edit_patent_document_path(@object, @document), :class=>"btn btn-default"
                - if can? :destroy, @document
                  = link_to '删除', [@object, @document], :method => :delete, :data => { :confirm => 'Are you sure?' }, :class=>"btn btn-default"
              - elsif @category == Setting.documents.category_thesis
                - if can? :update, @document
                  = link_to '编辑', edit_thesis_document_path(@object, @document), :class=>"btn btn-default"
                - if can? :destroy, @document
                  = link_to '删除', [@object, @document], :method => :delete, :data => { :confirm => 'Are you sure?' }, :class=>"btn btn-default"
    %br

    = render "show"