config/routes.rb
Pearl::Application.routes.draw do
  devise_for :users

  resources :users, :only => [:index, :show, :destroy] do
    post :select_group, :on => :collection
    get :edit_profile, :on => :collection
    post :update_profile, :on => :collection
    get :cancel_user, :on => :collection
  end

  resources :projects do
    get :finish, :on => :collection
    resources :documents
  end

  resources :papers do
    resources :documents
  end

  resources :patents do
    resources :documents
  end

  match '/theses/my' => 'theses#my'
  resources :theses do
    resources :documents
  end

  resources :reviews, :only => [:create, :destroy]

  match '/dailies/my(/:date)' => 'dailies#my'
  match '/dailies/group(/:date)' => 'dailies#group'
  match '/dailies/subgroup(/:date)' => 'dailies#subgroup'
  resources :dailies, :only => [:index, :show, :edit, :create, :update]

  resources :comments, :only => [:create, :destroy]

  match '/plans/user(/:id)' => 'plans#user'
  resources :plans do
    get :update_status, :on => :collection
  end

  resources :groups

  match '/home/index/(/:all)' => 'home#index'

  root :to => 'home#index'

end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  category   :integer
#  source     :string(255)
#  begin_at   :datetime
#  end_at     :datetime
#  status     :integer
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Project < ActiveRecord::Base
  has_many :documents
  belongs_to :user

  attr_accessible :title, :category, :source, :begin_at, :end_at, :status

  validates :title,     :presence => true
  validates :status,    :presence => true,
                        :numericality => {:only_integer => true}

  validates :user_id,   :presence => true
end

app/controllers/projects_controller.rb
# coding: utf-8

class ProjectsController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource :except => [:create]

  def index
    @projects = []
    if current_user.group
      root_group = get_root_group(current_user)
      all_projects = Project.all
      all_projects.each do |project|
        if project.user and get_root_group(project.user) == root_group
          @projects << project
        end
      end
    end
    total_count = @projects.size
    @projects = @projects.select {|p| p.status != Setting.projects.status_finish}
    @not_finish_count = @projects.size
    @finish_count = total_count - @projects.size
  end

  def finish
    @projects = []
    if current_user.group
      root_group = get_root_group(current_user)
      all_projects = Project.all
      all_projects.each do |project|
        if get_root_group(project.user) == root_group
          @projects << project
        end
      end
    end
    total_count = @projects.size
    @projects = @projects.select {|p| p.status == Setting.projects.status_finish}
    @not_finish_count = total_count - @projects.size
    @finish_count = @projects.size

    render "index"
  end

  def show
    @object = Project.find(params[:id])
    @documents = @object.documents
  end

  def new
    @project = Project.new
    @users = get_my_group_users
  end

  def edit
    @project = Project.find(params[:id])
    @users = get_my_group_users
  end

  def create
    user_id = params[:project].delete(:user_id)
    user = User.find(user_id)
    @project = Project.new(params[:project])
    @project.user = user

    if @project.save
      history = History.new(:category=>Setting.histories.category_project, :detail_id=>@project.id, :action=>Setting.histories.action_create)
      history.user = current_user    #当前正在操作的user，而不是负责人
      history.group = get_root_group(current_user)
      history.save
      redirect_to @project
    else
      flash[:error] = "输入内容缺失或存在错误，新建项目失败！"
      redirect_to new_project_url
    end

    authorize! :create, @project
  end

  def update
    user_id = params[:project].delete(:user_id)
    user = User.find(user_id)
    @project = Project.find(params[:id])
    @project.user = user

    if @project.update_attributes(params[:project])
      history = History.new(:category=>Setting.histories.category_project, :detail_id=>@project.id, :action=>Setting.histories.action_update)
      history.user = current_user    #当前正在操作的user，而不是负责人
      history.group = get_root_group(current_user)
      history.save
      redirect_to @project
    else
      flash[:error] = "输入内容缺失或存在错误，编辑项目失败！"
      redirect_to edit_project_url(@project)
    end
  end

  def destroy
    @project = Project.find(params[:id])
    history = History.new(:category=>Setting.histories.category_project, :detail_id=>@project.id, :action=>Setting.histories.action_destroy)
    history.user = current_user    #当前正在操作的user，而不是负责人
    history.group = get_root_group(current_user)
    history.save
    @project.destroy

    redirect_to projects_url
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def generate_all_project_categories
    [
      [Setting.projects.category_vertical_string, Setting.projects.category_vertical],
      [Setting.projects.category_horizontal_string, Setting.projects.category_horizontal]
    ]
  end

  def generate_all_project_status
    [
      [Setting.projects.status_plan_string, Setting.projects.status_plan],
      [Setting.projects.status_writing_string, Setting.projects.status_writing],
      [Setting.projects.status_applying_string, Setting.projects.status_applying],
      [Setting.projects.status_reviewing_string, Setting.projects.status_reviewing],
      [Setting.projects.status_proceeding_string, Setting.projects.status_proceeding],
      [Setting.projects.status_acceptance_string, Setting.projects.status_acceptance],
      [Setting.projects.status_finish_string, Setting.projects.status_finish]
    ]
  end

  def get_project_category_string(category)
    if category == Setting.projects.category_vertical
      Setting.projects.category_vertical_string
    elsif category == Setting.projects.category_horizontal
      Setting.projects.category_horizontal_string
    end
  end

  def get_project_status_string(status)
    if status == Setting.projects.status_plan
      Setting.projects.status_plan_string
    elsif status == Setting.projects.status_writing
      Setting.projects.status_writing_string
    elsif status == Setting.projects.status_applying
      Setting.projects.status_applying_string
    elsif status == Setting.projects.status_reviewing
      Setting.projects.status_reviewing_string
    elsif status == Setting.projects.status_proceeding
      Setting.projects.status_proceeding_string
    elsif status == Setting.projects.status_acceptance
      Setting.projects.status_acceptance_string
    elsif status == Setting.projects.status_finish
      Setting.projects.status_finish_string
    end
  end
end

app/views/projects/_form.html.haml
= form_for @project, :html=>{:class=>"form-horizontal"} do |f|
  - if @project.errors.any?
    #error_explanation
      %h2= "#{pluralize(@project.errors.count, "error")} prohibited this project from being saved:"
      %ul
        - @project.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label "名称", :class=>"col-md-2 control-label"
    .col-md-3
      = f.text_field :title, :class=>"form-control"

  .form-group
    = f.label "负责人", :class=>"col-md-2 control-label"
    .col-md-3
      = f.select :user_id, @users.map{|u| [u.name, u.id]}, {:selected=>(@project.user ? @project.user.id : nil)}, {:class=>"form-control"}

  .form-group
    = f.label "类别", :class=>"col-md-2 control-label"
    .col-md-3
      = f.select :category, generate_all_project_categories, {:selected=>@project.category}, {:class=>"form-control"}

  .form-group
    = f.label "来源", :class=>"col-md-2 control-label"
    .col-md-3
      = f.text_field :source, :class=>"form-control"

  .form-group
    = f.label "开始时间", :class=>"col-md-2 control-label"
    .col-md-3
      = f.text_field :begin_at, :class=>"form-control"

  .form-group
    = f.label "结束时间", :class=>"col-md-2 control-label"
    .col-md-3
      = f.text_field :end_at, :class=>"form-control"

  .form-group
    = f.label "状态", :class=>"col-md-2 control-label"
    .col-md-3
      = f.select :status, generate_all_project_status, {:selected=>@project.status}, {:class=>"form-control"}

  .form-group
    .col-md-3.col-md-offset-2
      = f.submit '保存', :class=>"btn btn-success"

<script type="text/javascript">
$('#project_begin_at').datepicker({
format: "yyyy-mm-dd",
weekStart: 1,
todayBtn: "linked",
language: "zh-CN"
});

$('#project_end_at').datepicker({
format: "yyyy-mm-dd",
weekStart: 1,
todayBtn: "linked",
language: "zh-CN"
});
</script>

app/views/projects/_sub_navbar.html.haml
%h2.page-header
  .row
    .col-md-8
      = @object.title
    .col-md-4
      = link_to "主页", project_path(@object), :class=>"btn btn-default", :class=> (controller_name=="projects" ? "btn btn-primary":"btn btn-default")
      = link_to "文档", project_documents_path(@object), :class=> (controller_name=="documents" ? "btn btn-primary":"btn btn-default")
      = link_to "文件", "#", :class=>"btn btn-default"
      = link_to "任务", "#", :class=>"btn btn-default"
      = link_to "回顾", "#", :class=>"btn btn-default"

app/views/projects/edit.html.haml
%h1.page-header 编辑项目

= render 'form'

app/views/projects/index.html.haml
- provide(:title, "项目管理")

%h1.page-header 项目管理

.row
  .col-md-9
    .well
      .row
        .col-md-3.col-md-offset-5
          = link_to '新建项目', new_project_path, :class=>"btn btn-lg btn-success"

%br

%h4.black-link
  = link_to "#{@not_finish_count}个正在进行的项目", projects_path
  = link_to "#{@finish_count}个已完成的项目", finish_projects_path

- @projects.each_slice(3) do |slice|
  .row
    - slice.each do |project|
      .col-md-3.black-link
        %a{:href=>project_path(project)}
          .offer.offer-danger
            .shape
              .shape-text hot
            .offer-content
              %h4.lead= project.title
              %p
                = "负责人：#{project.user && project.user.name}"
                %br
                = "类别：#{get_project_category_string(project.category)}&nbsp;&nbsp;&nbsp;&nbsp;状态：#{get_project_status_string(project.status)}".html_safe

app/views/projects/new.html.haml
%h1.page-header 新建项目

= render 'form'

app/views/projects/show.html.haml
= render "sub_navbar"

.row
  .col-md-5
    .panel.panel-info
      .panel-heading
        %h3.panel-title 项目信息
      .panel-body
        %table.table.table-bordered
          %tr
            %th.active 负责人
            %td= @object.user ? @object.user.name : nil
          %tr
            %th.active 类别
            %td= get_project_category_string(@object.category)
          %tr
            %th.active 来源
            %td= @object.source
          %tr
            %th.active 开始时间
            %td= @object.begin_at and @object.begin_at.strftime("%Y年%m月%d日")
          %tr
            %th.active 结束时间
            %td= @object.end_at and @object.end_at.strftime("%Y年%m月%d日")
          %tr
            %th.active 状态
            %td= get_project_status_string(@object.status)

        - if can? :update, @object
          = link_to '编辑', edit_project_path(@object), :class=>"btn btn-primary"
        - if can? :destroy, @object
          = link_to '删除', @object, :method => :delete, :data => { :confirm => 'Are you sure?' }, :class=>"btn btn-danger"

  .col-md-7
    .panel.panel-danger
      .panel-heading
        %h3.panel-title 项目动态
      .panel-body
        %table.table.table-hover
          - @documents.each do |document|
            %tr
              %td
                .row
                  .col-md-7
                    = link_to document.title, [@object, document]
                  .col-md-2
                    = document.user && document.user.name
                  .col-md-3
                    = document.created_at.strftime("%m-%d %H:%M")

        = link_to '新建文档', new_project_document_path(@object), :class=>"btn btn-default"