config/routes.rb
Pearl::Application.routes.draw do
  devise_for :users

  resources :users, :only => [:index, :show, :destroy] do
    post :select_group, :on => :collection
    get :edit_profile, :on => :collection
    post :update_profile, :on => :collection
    get :cancel_user, :on => :collection
  end

  resources :projects do
    get :finish, :on => :collection
    resources :documents
  end

  resources :papers do
    resources :documents
  end

  resources :patents do
    resources :documents
  end

  match '/theses/my' => 'theses#my'
  resources :theses do
    resources :documents
  end

  resources :reviews, :only => [:create, :destroy]

  match '/dailies/my(/:date)' => 'dailies#my'
  match '/dailies/group(/:date)' => 'dailies#group'
  match '/dailies/subgroup(/:date)' => 'dailies#subgroup'
  resources :dailies, :only => [:index, :show, :edit, :create, :update]

  resources :comments, :only => [:create, :destroy]

  match '/plans/user(/:id)' => 'plans#user'
  resources :plans do
    get :update_status, :on => :collection
  end

  resources :groups

  match '/home/index/(/:all)' => 'home#index'

  root :to => 'home#index'

end

app/models/paper.rb
# == Schema Information
#
# Table name: papers
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  magazine   :string(255)
#  status     :integer
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Paper < ActiveRecord::Base
  has_many :documents
  belongs_to :user

  attr_accessible :title, :magazine, :status

  validates :title,     :presence => true
  validates :status,    :presence => true,
                        :numericality => {:only_integer => true}

  validates :user_id,   :presence => true
end

app/controllers/papers_controller.rb
# coding: utf-8

class PapersController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource :except => [:create]

  def index
    @papers = []
    if current_user.group
      root_group = get_root_group(current_user)
      all_papers = Paper.all
      all_papers.each do |paper|
        if paper.user and get_root_group(paper.user) == root_group
          @papers << paper
        end
      end
    end
  end

  def show
    @object = Paper.find(params[:id])
    @documents = @object.documents
  end

  def new
    @paper = Paper.new
    @users = get_my_group_users
  end

  def edit
    @paper = Paper.find(params[:id])
    @users = get_my_group_users
  end

  #load_and_authorize_resource会先构造一个paper对象，因为user_id不可以直接赋值，
  #在构造paper对象时就会出错，解决方案是对create单独做处理
  def create
    user_id = params[:paper].delete(:user_id)
    user = User.find(user_id)
    @paper = Paper.new(params[:paper])
    @paper.user = user

    if @paper.save
      history = History.new(:category=>Setting.histories.category_paper, :detail_id=>@paper.id, :action=>Setting.histories.action_create)
      history.user = current_user    #当前正在操作的user，而不是负责人
      history.group = get_root_group(current_user)
      history.save
      redirect_to @paper
    else
      flash[:error] = "输入内容缺失或存在错误，新建论文失败！"
      redirect_to new_paper_url
    end

    authorize! :create, @paper
  end

  def update
    user_id = params[:paper].delete(:user_id)
    user = User.find(user_id)
    @paper = Paper.find(params[:id])
    @paper.user = user

    if @paper.update_attributes(params[:paper])
      history = History.new(:category=>Setting.histories.category_paper, :detail_id=>@paper.id, :action=>Setting.histories.action_update)
      history.user = current_user    #当前正在操作的user，而不是负责人
      history.group = get_root_group(current_user)
      history.save
      redirect_to @paper
    else
      flash[:error] = "输入内容缺失或存在错误，编辑论文失败！"
      redirect_to edit_paper_url(@paper)
    end
  end

  def destroy
    @paper = Paper.find(params[:id])
    history = History.new(:category=>Setting.histories.category_paper, :detail_id=>@paper.id, :action=>Setting.histories.action_destroy)
    history.user = current_user    #当前正在操作的user，而不是负责人
    history.group = get_root_group(current_user)
    history.save
    @paper.destroy

    redirect_to papers_url
  end
end

app/helpers/papers_helper.rb
module PapersHelper
  def generate_all_paper_status
    [
      [Setting.papers.status_submit_string, Setting.papers.status_submit],
      [Setting.papers.status_accept_string, Setting.papers.status_accept],
      [Setting.papers.status_publish_string, Setting.papers.status_publish]
    ]
  end

  def get_paper_status_string(status)
    if status == Setting.papers.status_submit
      Setting.papers.status_submit_string
    elsif status == Setting.papers.status_accept
      Setting.papers.status_accept_string
    elsif status == Setting.papers.status_publish
      Setting.papers.status_publish_string
    end
  end
end

app/views/papers/_form.html.haml
= form_for @paper, :html=>{:class=>"form-horizontal"} do |f|
  - if @paper.errors.any?
    #error_explanation
      %h2= "#{pluralize(@paper.errors.count, "error")} prohibited this paper from being saved:"
      %ul
        - @paper.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label "题目", :class=>"col-md-2 control-label"
    .col-md-3
      = f.text_field :title, :class=>"form-control"

  .form-group
    = f.label "作者", :class=>"col-md-2 control-label"
    .col-md-3
      = f.select :user_id, @users.map{|u| [u.name, u.id]}, {:selected=>(@paper.user ? @paper.user.id : nil)}, {:class=>"form-control"}

  .form-group
    = f.label "期刊", :class=>"col-md-2 control-label"
    .col-md-3
      = f.text_field :magazine, :class=>"form-control"

  .form-group
    = f.label "状态", :class=>"col-md-2 control-label"
    .col-md-3
      = f.select :status, generate_all_paper_status, {:selected=>@paper.status}, {:class=>"form-control"}

  .form-group
    .col-md-3.col-md-offset-2
      = f.submit '保存', :class=>"btn btn-default"

app/views/papers/_sub_navbar.html.haml
%h2.page-header
  .row
    .col-md-8
      = @object.title
    .col-md-4
      = link_to "主页", paper_path(@object), :class=>"btn btn-default", :class=> (controller_name=="papers" ? "btn btn-primary":"btn btn-default")
      = link_to "文档", paper_documents_path(@object), :class=> (controller_name=="documents" ? "btn btn-primary":"btn btn-default")
      = link_to "文件", "#", :class=>"btn btn-default"
      = link_to "任务", "#", :class=>"btn btn-default"
      = link_to "回顾", "#", :class=>"btn btn-default"

app/views/papers/index.html.haml
- provide(:title, "论文管理")

%h1.page-header 论文管理

.row
  .col-md-9
    .well
      .row
        .col-md-3.col-md-offset-5
          = link_to '新建论文', new_paper_path, :class=>"btn btn-lg btn-success"

%br

- @papers.each_slice(3) do |slice|
  .row
    - slice.each do |paper|
      .col-md-3.black-link
        %a{:href=>paper_path(paper)}
          .offer.offer-danger
            .shape
              .shape-text hot
            .offer-content
              %h4.lead= paper.title
              %p
                = "作者：#{paper.user && paper.user.name}"
                %br
                = "期刊：#{paper.magazine}"
                %br
                = "状态：#{get_paper_status_string(paper.status)}"

app/views/papers/show.html.haml
= render "sub_navbar"

.row
  .col-md-5
    .panel.panel-info
      .panel-heading
        %h3.panel-title 论文信息
      .panel-body
        %table.table.table-bordered
          %tr
            %th.active 作者
            %td= @object.user ? @object.user.name : nil
          %tr
            %th.active 期刊
            %td= @object.magazine
          %tr
            %th.active 状态
            %td= get_paper_status_string(@object.status)

        - if can? :update, @object
          = link_to '编辑', edit_paper_path(@object), :class=>"btn btn-primary"
        - if can? :destroy, @object
          = link_to '删除', @object, :method => :delete, :data => { :confirm => 'Are you sure?' }, :class=>"btn btn-danger"

  .col-md-7
    .panel.panel-danger
      .panel-heading
        %h3.panel-title 论文动态
      .panel-body
        %table.table.table-hover
          - @documents.each do |document|
            %tr
              %td
                .row
                  .col-md-7
                    = link_to document.title, [@object, document]
                  .col-md-2
                    = document.user && document.user.name
                  .col-md-3
                    = document.created_at.strftime("%m-%d %H:%M")

        = link_to '新建文档', new_paper_document_path(@object), :class=>"btn btn-default"